# reference: https://honye.github.io/posts/eaaf4b45.html
name: Hexo CI GAD

on: 
  push:
    branches: 
      - hexo

jobs:
  Hexo-CI-GAD:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      
    - name: Use Node.js 12.x
      uses: actions/setup-node@v1
      with:
        node-version: 12.x

    - name: Use cache
      uses: actions/cache@v1
      with:
        path: ~/.npm
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-

    - name: Setup Hexo
      run: |
        npm install hexo-cli -g
        npm install
     
    - name: Generate
      run: |
        hexo clean
        hexo g
        
    - name: Deploy
      env:
        GH_NAME: moreant
        GH_EMAIL: 552191481@qq.com
        GH_REF: github.com/moreant/moreant.github.io.git
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git config --global user.name $GH_NAME
        git config --global user.email $GH_EMAIL
        git clone https://"$GH_REF" deploy
        cd deploy
        git checkout master
        cd ../
        mv deploy/.git/ ./public/
        cd ./public/
        git add --all .
        git commit -m "CI built at `date +"%Y-%m-%d %H:%M:%S"`"
        git remote add origin https://"$GITHUB_TOKEN"@"$GH_REF"
        git push --force "https://"$GITHUB_TOKEN"@"$GH_REF"" master:master
